### ISSUE TITLE
Custom Fonts?

### ISSUE THREAD

**Issue by Spacelapp** [franklinsch/iOSDrawTextAnimation#1]
Does this thing only animate system fonts? What about custom fonts?

**Comment by franklinsch** [comment]
It relies on `CTFontCreatePathForGlyph`, which I think does support custom fonts. I'd suggest to give it a try, and let me know!

I'll try it myself, too.

**Comment by Spacelapp** [comment]
For me it doesn't work :/

**Comment by franklinsch** [comment]
What font did you try it with?
Are you sure the font works, ie you can create a label using it and see it properly in the Simulator?

**Comment by Spacelapp** [comment]
Ah it worked! :dancer: 
I forgot to set "Fonts provided by application" :D

**Comment by franklinsch** [comment]
Great to hear! :smiley:
