### ISSUE TITLE
Is it possible to have the text fill itself after the end of the animation?

### ISSUE THREAD

**Issue by cyrilzakka** [franklinsch/iOSDrawTextAnimation#7]

**Comment by franklinsch** [comment]
Good idea.
Not sure what's the best way to implement this yet. Any suggestions?

**Comment by cyrilzakka** [comment]
My way should by no means be considered good, but simply a quick fix to test out the animation. I'll have a better fix by the end of next week hopefully. Anyway, I just created a textViewFill (the same way you created the text view but with a white fill color instead of clear) and I animate its opacity at 80% of the animation duration. Preferably, I'd like to animate the opacity of each layer as soon as it finishes it drawing. Anyway, great thing you got here!

**Comment by franklinsch** [comment]
Cool, looking forward to it! Could you create a Pull Request if you do work on it?
Thanks for the help!

I think there should be customization options for the fill animation's speed, color, and delay (again, absolute or relative to the stroke animation). I'll be working on it in a couple of weeks.

**Comment by TheLDB** [comment]
Any update on this?
